### ISSUE TITLE
Smooth tank controls when moving and rotating

### ISSUE THREAD

**Issue by Sebeb** [dhubber/PillsGame#25]
I'm really not sure why, but moving whilst rotating in tank movement mode seems to be clunky. At the moment I'm manually rotating the player every frame. Applying an angular force fixes the problem, but also requires unlocking the player rigidbody's rotation, which allows it to roll on walls etc. Any ideas for fixes would be appreciated.

**Comment by dhubber** [comment]
Yes, confirmed.  Will have a think about this.

**Comment by Sebeb** [comment]
I think I got this one! But please reopen if it's not quite gotten yet.
