### ISSUE TITLE
Rename repository?

### ISSUE THREAD

**Issue by dhubber** [dhubber/PillsGame#3]
We can in principle rename the repository if we wish (now there's a proper name rather than get stuck with the working title).

**Comment by Sebeb** [comment]
Sounds good, although I expect YouHaveToTakeYourPills may be slightly over GitHub's length limit haha. Maybe just 'PillsGame' or 'ProjectPills'?

**Comment by dhubber** [comment]
Hmmm, PillsGame sounds fine :-).  Definitely more appropriate than our working title!

**Comment by Sebeb** [comment]
Do it!

**Comment by dhubber** [comment]
The deed is done!  I just re-cloned the repository to be sure nothing goes wrong though ;-)

**Comment by Sebeb** [comment]
Sweet! Mazed up is dead, long live Pills Game!
