### ISSUE TITLE
Which platform!?

### ISSUE THREAD

**Issue by dhubber** [dhubber/PillsGame#40]
So, we didn't discuss something important, which platform(s) are we aiming for?  The way it's going we're aiming for desktop since it seems hard to see how we can adapt it to mobile.

**Comment by Sebeb** [comment]
Yeah, as it stands, it's completely reliant on using a keyboard/controller as input. That said, the controls are very minimal (just movement, and 'okay'), so maybe it could work on mobile using a virtual joystick. Maybe the kind where you can press anywhere on the screen and drag to determine the direction in which you move. But many pills and variables would require tweaking first. If we were to go down that route (something I definitely think is worth exploring), I'd definitely say aim for a complete PC release first.
So I'd say for the time being, it's best to just target PC, Mac and Windows. I Covertakt liebe constantly develop and test on my Mac, and then test it on Windows as well, and so far I haven't noticed any issues exclusive to one platform, other than when Unity/GitHub don't copy so my inspector assigned variables and the whole thing just doesn't work when switching platforms :rage: So while I haven't tested on Linux at all, I think we can be reasonably certain that that should be compatible by default, although it would be good to test that at some stage. 
Also, I made sure that the level complete screen either says 'Press enter to proceed', or 'Press A to proceed', depending on whether the current input is a controller (Xbox controller) or keyboard. At least the back end is there, I still need to change the actual variable :stuck_out_tongue_closed_eyes: But I'm definitely aiming to have the whole game playable exclusively by controller, without having to touch the keyboard.

**Comment by dhubber** [comment]
ok, so let's concentrate on PC for now.  I at least have my Ubuntu Linux laptop to at least test that build (if there's a Linux build already, I can even try it tonight just to see how it's playing?).  Then we can release it wherever and think about mobile!  Any ideas though?  Itch.io is one I've used with other collaborators before for releasing free Unity-made games.

**Comment by dhubber** [comment]
Okay, I just made a Linux build and tried it on Ubuntu and it worked absolutely fine.  Kind of shocked really, hehe :-) .  So hopefully those previous issues I thought were Mac-only issues were just wrong branches or not some other repository issue and we can safely assume it should work on all 3 platforms!

**Comment by Sebeb** [comment]
Praise be to Unity :pray: :pray: :stuck_out_tongue_closed_eyes:
